version: "3"

services:
    postgres:
        image: postgres:12.3-alpine
        restart: always
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_USER: ${POSTGRES_USER}
        volumes:
            - ./postgres-data/:/var/lib/postgresql/data/
        ports:
            - ${POSTGRES_PORT}:5432

    pgadmin:
        image: dpage/pgadmin4:4.23
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
            PGADMIN_LISTEN_PORT: 80
        ports:
            - ${PGADMIN_PORT}:80
        volumes:
            - ./pgadmin-data/:/var/lib/pgadmin/
        depends_on:
            - postgres
